name = "Create: Just for Fun"
author = "First-Non-Interesting-Username"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60d8835edc17cbaf242abc6e84db23aea59a3f306e3c0279feafa0ac1a0e2ae0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "saves/default/datapacks"
