name = "Create: Just for Fun"
author = "First-Non-Interesting-Username"
version = "2026.23"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d11bd61f58a575e123d6b739b8432eda520912f0d7d0aba8ab99ddff2c69872d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "saves/default/datapacks"
