name = "Create: Just for Fun"
author = "First-Non-Interesting-Username"
version = "2026.27"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "131c72efc09db2d78fe0047d4ce421ce9baad211ca434629e8205247ab698e1e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "saves/default/datapacks"
