name: Format .toml files

on: 
    workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: uncenter/setup-taplo@b18c8c8302695fe63d6853bc004006215ac52b91 # v2
        with:
          version: "0.10.0"

      - name: Check formatting
        run: taplo fmt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "style: toml formatting"
          title: "style: toml formatting"
          body: "This PR contains code formatted by taplo"
          branch: "style/toml-formatting"
          base: "main"