name: Create github release

on:
  schedule:
    - cron: '45 17 * * 5'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Export to .mrpack
        uses: hudsonm62/packwiz-action@538bcd35d3a4810f35ef6f51b0b65be8191b28bf # v1
        with:
          args: modrinth export

      - name: Get release name
        id: release_name
        run: echo "value=$(date +'%Y.%V')" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3
        with:
          tag_name: ${{ steps.release_name.outputs.value }}
          name: ${{ steps.release_name.outputs.value }}
          generate_release_notes: true
          files: "*./*.mrpack"

      - name: Publish Modpack to Modrinth
        uses: cloudnode-pro/modrinth-publish@8dc596b20b94959bf244180235d90729d05a674f # v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project-id: 'Oz2C6Bff' 
          version: ${{ steps.release_name.outputs.value }}
          file: ./*.mrpack
          changelog: ${{ steps.create_release.outputs.body }}
          version-type: 'release'
          loaders: 'neoforge'
          game-versions: |
            1.21.1